/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HO;

import java.util.Arrays;
import java.util.List;

import HO.data.Student;
import HO.list.Comparator;
import HO.list.MatriculationNumberComparator;
import HO.list.PrenameComparator;
import HO.sort.BubbleSort;
import HO.sort.SelectionSort;
import HO.sort.Sortable;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Student s1 = new Student("Donald", "Duck", 56, 55);
        Student s2 = new Student("Cooper", "Sheldon", 1, 999);
        Student s3 = new Student("Alice", "Cooper", 56, 11);
        Student s4 = new Student("Mosby", "Ted", 1, 100);

        List<Student> list = Arrays.asList(s1, s2, s3, s4);

        printList(list, "Unsortiert");

        sortAndPrint(list, new BubbleSort<Student>(), new MatriculationNumberComparator());
        sortAndPrint(list, new SelectionSort<Student>(), new PrenameComparator());
    }

    private static void sortAndPrint( List<Student> list, Sortable<Student> algorithm, Comparator<Student> comparator ) {

        System.out.println("Sort Algorithm " + algorithm.getClass().getSimpleName() + " Comparator"  + comparator.getClass().getSimpleName());
        algorithm.sort( list, comparator);

        //printing
        for (int i = 0; i < list.size(); i++) {
            System.out.println((i + 1) + ", " + list.get(i));
        }
    }

    private static void printList( List<Student> list, String headline ) {
        System.out.println(headline);
        for (int i = 0; i < list.size(); i++) {
            System.out.println((i + 1) + ", " + list.get(i));
        }
    }
}
